version: "3"
services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: as-kiwix-serve
      APP_PORT: 3000

  server:
    image: ghcr.io/kiwix/kiwix-serve:3.7.0-2
    ports:
      - 8888:8080
    volumes:
       - ${APP_DATA_DIR}/zims:/data
    command:
      - 'wget https://download.kiwix.org/zim/wikipedia/wikipedia_es_all_mini_2024-06.zim'
    restart: unless-stopped
