version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: as-kiwix
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/kiwix/kiwix-serve:3.7.0-2
    restart: on-failure
    command: "*.zim"
    environment:
      - 'DOWNLOAD=https://download.kiwix.org/zim/wikipedia_es_all.zim'
    volumes:
      - ${APP_DATA_DIR}/data/zim:/data:rw
    ports:
      - "8080:8080"