version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: as-kiwix-serve
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/kiwix/kiwix-serve:3.7.0-2
    restart: on-failure
    command: "*.zim"
    environment:
      # Puedes agregar variables de entorno personalizadas si son necesarias
      # EJEMPLO: KIWI_ENV_VAR: valor
    volumes:
      - ${APP_DATA_DIR}/kiwix/data:/data
    ports:
      - "8080:8080"
